// Generated by scripts/sync-tiled-assets.mjs. Do not edit by hand.

export type TiledWorldRoomManifestEntry = {
  id: string;
  fileName: string;
  mapPath: string;
  worldX: number;
  worldY: number;
  width: number;
  height: number;
};

export const TILED_WORLD_SOURCE = "H:/Tiled/ElPillador/Mazmorra.world" as const;

export const tiledWorldRooms = [
  {
    "id": "Boss-P",
    "fileName": "Grecia/Boss-P.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/Boss-P.json",
    "worldX": 768,
    "worldY": 4144,
    "width": 384,
    "height": 384
  },
  {
    "id": "CP-G1",
    "fileName": "Grecia/CP-G1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/CP-G1.json",
    "worldX": 384,
    "worldY": 2608,
    "width": 384,
    "height": 384
  },
  {
    "id": "DS-E1",
    "fileName": "Entrada/DS-E1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/DS-E1.json",
    "worldX": 1536,
    "worldY": 1840,
    "width": 384,
    "height": 384
  },
  {
    "id": "DS-E2",
    "fileName": "Entrada/DS-E2.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/DS-E2.json",
    "worldX": 768,
    "worldY": 2224,
    "width": 384,
    "height": 384
  },
  {
    "id": "DS-G1",
    "fileName": "Grecia/DS-G1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/DS-G1.json",
    "worldX": 768,
    "worldY": 3376,
    "width": 384,
    "height": 384
  },
  {
    "id": "DS-G2",
    "fileName": "Grecia/DS-G2.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/DS-G2.json",
    "worldX": 384,
    "worldY": 4144,
    "width": 384,
    "height": 384
  },
  {
    "id": "MG-G1",
    "fileName": "Grecia/MG-G1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/MG-G1.json",
    "worldX": 384,
    "worldY": 3376,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-E1",
    "fileName": "Entrada/PZ-E1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-E1.json",
    "worldX": 1536,
    "worldY": 2224,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-E2",
    "fileName": "Entrada/PZ-E2.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-E2.json",
    "worldX": 1920,
    "worldY": 2224,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-E3",
    "fileName": "Entrada/PZ-E3.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-E3.json",
    "worldX": 1536,
    "worldY": 2608,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-E4",
    "fileName": "Entrada/PZ-E4.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-E4.json",
    "worldX": 1152,
    "worldY": 2224,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-G1",
    "fileName": "Grecia/PZ-G1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-G1.json",
    "worldX": 768,
    "worldY": 2608,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-G2",
    "fileName": "Grecia/PZ-G2.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-G2.json",
    "worldX": 768,
    "worldY": 2992,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-G3",
    "fileName": "Grecia/PZ-G3.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-G3.json",
    "worldX": 768,
    "worldY": 3760,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-G4",
    "fileName": "Grecia/PZ-G4.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-G4.json",
    "worldX": 384,
    "worldY": 3760,
    "width": 384,
    "height": 384
  },
  {
    "id": "PZ-R1",
    "fileName": "Correr/PZ-R1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/PZ-R1.json",
    "worldX": 2304,
    "worldY": 2096,
    "width": 512,
    "height": 512
  },
  {
    "id": "SR18",
    "fileName": "Entrada/SR18.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SR18.json",
    "worldX": 1920,
    "worldY": 2608,
    "width": 384,
    "height": 384
  },
  {
    "id": "SR2",
    "fileName": "Entrada/SR2.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SR2.json",
    "worldX": 1536,
    "worldY": 2992,
    "width": 384,
    "height": 384
  },
  {
    "id": "SR4",
    "fileName": "Grecia/SR4.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SR4.json",
    "worldX": 0,
    "worldY": 3376,
    "width": 384,
    "height": 384
  },
  {
    "id": "SR9",
    "fileName": "Grecia/SR9.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SR9.json",
    "worldX": 384,
    "worldY": 2992,
    "width": 384,
    "height": 384
  },
  {
    "id": "SS1",
    "fileName": "Entrada/SS1.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SS1.json",
    "worldX": 1920,
    "worldY": 2992,
    "width": 384,
    "height": 384
  },
  {
    "id": "SS12",
    "fileName": "Grecia/SS12.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SS12.json",
    "worldX": 1152,
    "worldY": 2992,
    "width": 384,
    "height": 384
  },
  {
    "id": "SS13",
    "fileName": "Entrada/SS13.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SS13.json",
    "worldX": 2304,
    "worldY": 2608,
    "width": 384,
    "height": 384
  },
  {
    "id": "SS7",
    "fileName": "Grecia/SS7.tmj",
    "mapPath": "/assets/game/data/tiled/rooms/SS7.json",
    "worldX": 0,
    "worldY": 2992,
    "width": 384,
    "height": 384
  }
] as const satisfies readonly TiledWorldRoomManifestEntry[];

export const tiledWorldRoomsById: Record<string, TiledWorldRoomManifestEntry> = Object.fromEntries(
  tiledWorldRooms.map((room) => [room.id, room]),
);
